---
deployment:
  tasks:
    - export DEPLOYPATH=/home/eudfp0im1mv1/
    - /bin/cp -r * $DEPLOYPATH
    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/css
